jobs:
  
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.1
      - run: dotnet build StarDex.Client/StarDex.Client.csproj
      - run: dotnet build Domain.Service/DomainService.ClientMVC/DomainService.ClientMVC.csproj
      - run: dotnet build Image.Service/Image.Client/Image.Client.csproj

  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.1
      - run: dotnet test Domain.Service/DomainService.Testing/DomainService.Testing.csproj
      - run: dotnet test Image.Service/Image.Testing/Image.Testing.csproj



name: cibuild

on: push

